apiVersion: v1
kind: ConfigMap

metadata:
  name: dealership-api-config
  namespace: dealership
  labels:
    app: dealership-api
    tier: backend

data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"

  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"

  SPRING_APPLICATION_NAME: "Dealership-api"

  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_SWAGGER_UI_ENABLED: "true"
