apiVersion: v1
kind: Service

metadata:
  name: dealership-api-service
  namespace: dealership
  labels:
    app: dealership-api
    tier: backend

spec:
  type: ClusterIP
  selector:
    app: dealership-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
